version: '3.9'

services:
  api:
    container_name: mate_api
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    command: /start.sh
    ports:
      - "8000:8000"
    volumes:
      - .backend:/backend
    expose:
      - 8000

  frontend:
    container_name: mate_frontend
    tty: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - frontend_build:/frontend/build
    depends_on:
      - api
  nginx:
    image: nginx:latest
    command: [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ]
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - api
      - frontend
volumes:
  frontend_build: