version: '3.9'

services:
  api:
    container_name: mate_api
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    command: /start.sh
    ports:
      - "8000:8000"
    volumes:
      - .backend:/backend
    expose:
      - 8000

  frontend:
    container_name: mate_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - "5173:5173"
    restart: 'always'
    command: npm run dev
